all:
	g++ -std=c++11 -I . -o chess \
	    model/Board.cpp \
	    model/Location.cpp \
	    model/Move.cpp \
	    model/Piece.cpp \
	    model/pieces/Pawn.cpp \
	    view/test.cpp \
	    view/BoardPrinter.cpp

